### ISSUE TITLE
KeyError: 'convertible_bonds' when request user info

### ISSUE THREAD

**Issue by Tim55667757** [Tim55667757/TKSBrokerAPI#121]
Affected tksbrokerapi v1.5.120.

```
% tksbrokerapi -u -v 10

...

TKSBrokerAPI.py     L:5328 DEBUG   [2023-01-22 01:26:29,883] Traceback (most recent call last):
  File "/Users/tim/projects/TKSBrokerAPI/tksbrokerapi/TKSBrokerAPI.py", line 5309, in Main
    trader.OverviewUserInfo(show=True)
  File "/Users/tim/projects/TKSBrokerAPI/tksbrokerapi/TKSBrokerAPI.py", line 4686, in OverviewUserInfo
    "allowed": [TKS_QUALIFIED_TYPES[item] for item in rawUserInfo["qualifiedForWorkWith"]],
  File "/Users/tim/projects/TKSBrokerAPI/tksbrokerapi/TKSBrokerAPI.py", line 4686, in <listcomp>
    "allowed": [TKS_QUALIFIED_TYPES[item] for item in rawUserInfo["qualifiedForWorkWith"]],
KeyError: 'convertible_bonds'
```

**Comment by Tim55667757** [comment]
Some values of `qualified_for_work_with`, field was added in REST API, but not documented: https://tinkoff.github.io/investAPI/faq_users/#qualified_for_work_with

New non-documented fields: `foreign_bonds_russian_law`, `convertible_bonds`, `russian_bonds_foreign_law`, `non_quoted_instruments` and `option`.

Fixed since TKSBrokerAPI v1.6.***
