### ISSUE TITLE
KeyError: 'name' occured in `Overview()` method

### ISSUE THREAD

**Issue by Tim55667757** [Tim55667757/TKSBrokerAPI#127]
```
python TKSBrokerAPI.py -o -v 10

Traceback (most recent call last):
  File "x:\work\projects\TKSBrokerAPI\tksbrokerapi\TKSBrokerAPI.py", line 5101, in Main
    trader.Overview(show=True, details="full")
  File "x:\work\projects\TKSBrokerAPI\tksbrokerapi\TKSBrokerAPI.py", line 1819, in Overview
    "name": curr["name"],
KeyError: 'name'
```

**Comment by Tim55667757** [comment]
Fixed in v1.6.dev154

Debug build: https://app.travis-ci.com/github/Tim55667757/TKSBrokerAPI/builds/260999666
PyPI artefact for testing: https://pypi.org/project/tksbrokerapi/1.6.dev154/
