### ISSUE TITLE
trader.Overview 

### ISSUE THREAD

**Issue by Patsantre** [Tim55667757/TKSBrokerAPI#131]
Добрый день!

При выполнении команды 
```
!tksbrokerapi -o --debug-level 10
```

Получаем следующий аутпут:
```
TKSBrokerAPI.py     L:4817 DEBUG   [2023-10-14 05:41:58,351] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
TKSBrokerAPI.py     L:4818 DEBUG   [2023-10-14 05:41:58,351] >>> TKSBrokerAPI module started at: [2023-10-14 05:41:58] UTC, it is [2023-10-14 05:41:58] local time
TKSBrokerAPI.py     L:4832 DEBUG   [2023-10-14 05:41:58,352] TKSBrokerAPI major.minor.build version used: [1.5.120]
TKSBrokerAPI.py     L:4833 DEBUG   [2023-10-14 05:41:58,352] Host CPU count: [2]
TKSBrokerAPI.py     L:111  DEBUG   [2023-10-14 05:41:58,352] Bearer token for Tinkoff OpenAPI set up from environment variable `TKS_API_TOKEN`. See https://tinkoff.github.io/investAPI/token/
TKSBrokerAPI.py     L:124  DEBUG   [2023-10-14 05:41:58,352] Main account ID [2021236928] set up from environment variable `TKS_ACCOUNT_ID`
TKSBrokerAPI.py     L:176  DEBUG   [2023-10-14 05:41:58,352] Broker API server: https://invest-public-api.tinkoff.ru/rest
TKSBrokerAPI.py     L:350  DEBUG   [2023-10-14 05:41:58,424] Local cache with raw instruments data is used: [/content/dump.json]. Last modified: [2023-10-14 05:09:45] UTC
TKSBrokerAPI.py     L:1682 DEBUG   [2023-10-14 05:41:58,425] Requesting portfolio of a client. Wait, please...
TKSBrokerAPI.py     L:1523 DEBUG   [2023-10-14 05:41:58,425] Requesting current actual user's portfolio. Wait, please...
TKSBrokerAPI.py     L:1548 DEBUG   [2023-10-14 05:41:58,788] Requesting current open positions in currencies and instruments. Wait, please...
TKSBrokerAPI.py     L:1573 DEBUG   [2023-10-14 05:41:59,042] Requesting current actual pending limit orders. Wait, please...
TKSBrokerAPI.py     L:1579 DEBUG   [2023-10-14 05:41:59,298] [0] records about pending limit orders received
TKSBrokerAPI.py     L:1597 DEBUG   [2023-10-14 05:41:59,299] Requesting current actual stop orders. Wait, please...
TKSBrokerAPI.py     L:1603 DEBUG   [2023-10-14 05:41:59,551] [0] records about stop orders received
TKSBrokerAPI.py     L:5195 DEBUG   [2023-10-14 05:41:59,558] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tksbrokerapi/TKSBrokerAPI.py", line 4942, in Main
    trader.Overview(show=True, details="full")
  File "/usr/local/lib/python3.10/dist-packages/tksbrokerapi/TKSBrokerAPI.py", line 1706, in Overview
    "name": curr["name"],
KeyError: 'name'

TKSBrokerAPI.py     L:5196 DEBUG   [2023-10-14 05:41:59,558] Please, check issues or request a new one at https://github.com/Tim55667757/TKSBrokerAPI/issues
TKSBrokerAPI.py     L:5207 ERROR   [2023-10-14 05:41:59,558] An issue occurred with TKSBrokerAPI module! See full debug log in [/content/TKSBrokerAPI.log] or run TKSBrokerAPI once again with the key `--debug-level 10`. Summary code: 255
TKSBrokerAPI.py     L:5211 DEBUG   [2023-10-14 05:41:59,558] >>> TKSBrokerAPI module work duration: [0:00:01.207338]
TKSBrokerAPI.py     L:5212 DEBUG   [2023-10-14 05:41:59,559] >>> TKSBrokerAPI module finished: [2023-10-14 05:41:59 UTC], it is [2023-10-14 05:41:59] local time
TKSBrokerAPI.py     L:5216 DEBUG   [2023-10-14 05:41:59,559] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
```

**Comment by Patsantre** [comment]
```
TKSBrokerAPI 1.5.120
```

**Comment by Tim55667757** [comment]
@Patsantre Добрый день! Проблема возникла в том году, из-за санкций. Ошибка исправлена ещё в #127, но, к сожалению, всё никак не удаётся выпустить стабильный релиз 1.6.

Версии 1.5 сейчас работать не будут, следует пользоваться фича-сборками 1.6.dev*, например, попробуйте вашу команду с этой версией: https://pypi.org/project/tksbrokerapi/1.6.dev155/
`pip install tksbrokerapi==1.6.dev155`

**Comment by Oleg444000** [comment]
Добрый день! релиз 1.6.  TypeError: NDFrame.to_excel() got an unexpected keyword argument 'encoding'

During handling of the above exception, another exception occurred:

**Comment by Tim55667757** [comment]
> Добрый день! релиз 1.6. $python3 tksbrokerapi --bonds-xlsx
> 
> TypeError: NDFrame.to_excel() got an unexpected keyword argument 'encoding'
> 
> During handling of the above exception, another exception occurred:

@Oleg444000 Добрый день!
Вынес эту ошибку в отдельную задачу, так как она не относится к текущей. Буду разбираться на следующей неделе в рамках #133

**Comment by Tim55667757** [comment]
Можно использовать любую dev-версию старше v1.6.dev155.

Например, **v1.6.dev245** (более оптимизированную и ускоренную)

PyPI:

```bash
pip install tksbrokerapi==1.6.dev245
```

https://pypi.org/project/tksbrokerapi/1.6.dev245/
