### ISSUE TITLE
No module named 'Templates'

### ISSUE THREAD

**Issue by Patsantre** [Tim55667757/TKSBrokerAPI#132]
Добрый день!

При запуске в гугл коллаб возникает следующая ситуация

```
!tksbrokerapi --debug-level=10
```

```
Traceback (most recent call last):
  File "/usr/local/bin/tksbrokerapi", line 5, in <module>
    from tksbrokerapi.TKSBrokerAPI import Main
  File "/usr/local/lib/python3.10/dist-packages/tksbrokerapi/TKSBrokerAPI.py", line 54, in <module>
    from Templates import *  # Some html-templates used by reporting methods in TKSBrokerAPI module
ModuleNotFoundError: No module named 'Templates'
```

**Comment by Tim55667757** [comment]
@Patsantre Добрый день! Это не проблема платформы, а особенности настройки вашей локальной установки Python.

Объяснение и решение проблемы описано [здесь](https://github.com/Tim55667757/TKSBrokerAPI/issues/122#issuecomment-1400916603) и [здесь](https://github.com/Tim55667757/TKSBrokerAPI/issues/122#issuecomment-1408673077) в комментариях #122
Внесено в документацию: [RU](https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/README.md#%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%B0), [EN](https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/README_EN.md#Import-errors)

Также, пока что следует пользоваться фича-сборками 1.6.dev*, например: [1.6.dev155](https://pypi.org/project/tksbrokerapi/1.6.dev155/)
`pip install tksbrokerapi==1.6.dev155`

**Comment by Tim55667757** [comment]
@Patsantre Если вы хотите использовать платформу внутри юпитер-ноутбука, попробуйте установить её в ядро, до импортов, аналогично, как показано в одном из примеров (первые две [In] строки): https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/docs/examples/HampelFilteringExample.ipynb

`!{sys.executable} -m pip install TKSBrokerAPI==1.6.dev155`

**Comment by Tim55667757** [comment]
Здравствуйте! Окончательно пофикшено в #142.
Использовать можно начиная с билда: https://pypi.org/project/tksbrokerapi/1.6.dev219/
